require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - vendor/**/*
    - db/schema.rb
    - config/environments/*.rb

  # Default formatter will be used if no `-f/--format` option is given.
  DefaultFormatter: progress
  # Cop names are displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the `--no-display-cop-names`
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding `DisplayStyleGuide`, or by giving the
  # `-S/--display-style-guide` option.
  DisplayStyleGuide: false
  # When specifying style guide URLs, any paths and/or fragments will be
  # evaluated relative to the base URL.
  StyleGuideBaseURL: https://rubystyle.guide
  # Documentation URLs will be constructed using the base URL.
  DocumentationBaseURL: https://docs.rubocop.org/rubocop
  # Extra details are not displayed in offense messages by default. Change
  # behavior by overriding ExtraDetails, or by giving the
  # `-E/--extra-details` option.
  ExtraDetails: false
  # Additional cops that do not reference a style guide rule may be enabled by
  # default. Change behavior by overriding `StyleGuideCopsOnly`, or by giving
  # the `--only-guide-cops` option.
  StyleGuideCopsOnly: false

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: 1

Layout/ExtraSpacing:
  AllowForAlignment: true
  AllowBeforeTrailingComments: true
  # ForceEqualSignAlignment: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 160

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false


Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousOperator:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/RedundantPercentQ:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/ModuleFunction:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
    - "spec/**/*.rb"

Metrics/AbcSize:
  Exclude:
    - "**/*.rake"
    - "db/**/*.rb"

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 14
  Exclude:
    - "db/migrate/**/*.rb"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

RSpec/NestedGroups:
  Max: 4
