name: Pull request workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUBY_VERSION: 3.2

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build Assets
        run: |
          bin/rails tailwindcss:build

      - name: Run RSpec
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres@localhost:5432/"
        run: |
          bundle exec rails db:setup
          bundle exec rspec
